version: "3"
services:
  vitae-bbs-frontend:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/workspace/vitae-bbs-frontend:cached
      - node_modules:/workspace/vitae-bbs-frontend/node_modules
      - "~/.aws:/home/vscode/.aws"
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  node_modules: